consumes:
    - application/json
definitions:
    apiError:
        properties:
            Code:
                format: int64
                type: integer
            Message:
                type: string
        type: object
        x-go-package: wallet/docs
    healthData:
        properties:
            ping:
                type: string
                x-go-name: Ping
        type: object
        x-go-package: wallet/docs
info:
    description: Documentation for finansiyer Service API
    title: finansiyer Service API.
    version: 1.0.0
paths:
    /banks:
        get:
            description: Returns response of bank result
            operationId: bankRequest
            responses:
                "200":
                    $ref: '#/responses/bankResponse'
            summary: GetBanks
    /health:
        get:
            description: Returns response of health result
            operationId: healthRequest
            responses:
                "200":
                    $ref: '#/responses/healthResponse'
            summary: Health
produces:
    - application/json
responses:
    healthResponse:
        description: Success
        schema:
            properties:
                data:
                    $ref: '#/definitions/healthData'
                result:
                    $ref: '#/definitions/apiError'
            type: object
schemes:
    - https
    - http
swagger: "2.0"
